# Generated by Django 5.1.2 on 2024-11-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.PositiveSmallIntegerField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('volumen', models.PositiveSmallIntegerField()),
                ('precio', models.PositiveSmallIntegerField()),
                ('notas_olfativas', models.CharField(max_length=100)),
            ],
        ),
    ]
